/**
 * Parametric part library. dims is the only place a millimetre is written.
 */

import type { BufferGeometry } from 'three';
import type { FrameId } from '../engine/kinematics.ts';
import { CHAIN_Z_MM } from '../engine/units.ts';
import {
  box,
  coneZ,
  hexPlate,
  merge,
  rodX,
  rodY,
  rodZ,
  stepper,
  torusZ,
} from './primitives.ts';

export type PartKind = 'printed' | 'plywood' | 'extrusion' | 'motor' | 'cots' | 'electronic' | 'accent';

export const KIND_COLOR: Record<PartKind, string> = {
  printed: '#E4D2A8',
  plywood: '#C9A56A',
  extrusion: '#2C2C2C',
  motor: '#151515',
  cots: '#8B939C',
  electronic: '#1E1E1E',
  accent: '#F5C400',
};

export interface PartDef {
  id: string;
  name: string;
  kind: PartKind;
  dims: Record<string, number>;
  qty: number;
  unitEur?: number;
  mount: { frame: FrameId; position: [number, number, number]; rotation?: [number, number, number] };
  repeats?: { position: [number, number, number]; rotation?: [number, number, number] }[];
  explodeDir?: [number, number, number];
  group: 'frame' | 'chain' | 'station' | 'yarn' | 'control' | 'work';
  note: string;
  build: (d: Record<string, number>) => BufferGeometry;
}

const P: PartDef[] = [
  {
    id: 'base',
    name: 'Hex plywood deck',
    kind: 'plywood',
    dims: { r: 230, t: 18 },
    qty: 1,
    unitEur: 18,
    mount: { frame: 'base', position: [0, 0, -9] },
    explodeDir: [0, 0, -1],
    group: 'frame',
    note: 'Everything datums off this. 18 mm birch, CNC or jigsaw.',
    build: (d) => hexPlate(d.r, d.t),
  },
  {
    id: 'leg',
    name: '2040 leg',
    kind: 'extrusion',
    dims: { h: 210, s: 20 },
    qty: 3,
    unitEur: 7,
    mount: { frame: 'base', position: [150, 0, 105] },
    repeats: [
      { position: [-75, 130, 105] },
      { position: [-75, -130, 105] },
    ],
    explodeDir: [0, 0, 1],
    group: 'frame',
    note: 'Tripod. T-nuts, no machining.',
    build: (d) => box(d.s, d.s, d.h),
  },
  {
    id: 'ring-table',
    name: 'Chain table',
    kind: 'printed',
    dims: { r: 168, t: 8 },
    qty: 1,
    unitEur: 6,
    mount: { frame: 'C', position: [0, 0, CHAIN_Z_MM - 14] },
    explodeDir: [0, 0, 1],
    group: 'chain',
    note: 'Rotates with C. The necklace of gates sits on this lip.',
    build: (d) => merge([torusZ(d.r, 7), rodZ(22, d.t + 6, 24, 4)]),
  },
  {
    id: 'hub',
    name: 'Turntable hub',
    kind: 'cots',
    dims: { r: 48, h: 22 },
    qty: 1,
    unitEur: 28,
    mount: { frame: 'C', position: [0, 0, CHAIN_Z_MM - 36] },
    explodeDir: [0, 0, -1],
    group: 'chain',
    note: 'Lazy-susan bearing. Buy, never print — this sets concentricity.',
    build: (d) => rodZ(d.r, d.h),
  },
  {
    id: 'motor-c',
    name: 'C-axis motor',
    kind: 'motor',
    dims: { s: 42, l: 40 },
    qty: 1,
    unitEur: 14,
    mount: { frame: 'base', position: [0, 0, 48], rotation: [180, 0, 0] },
    explodeDir: [0, 0, -1],
    group: 'chain',
    note: 'NEMA17 under the deck, GT2 belt to the hub.',
    build: (d) => stepper(d.s, d.l),
  },
  {
    id: 'skirt',
    name: 'Take-down skirt',
    kind: 'printed',
    dims: { r: 95, t: 6 },
    qty: 1,
    unitEur: 4,
    mount: { frame: 'Z', position: [0, 0, 0] },
    explodeDir: [0, 0, -1],
    group: 'work',
    note: 'Sprung ring the hanging fabric passes through so it cannot climb.',
    build: (d) => torusZ(d.r, d.t),
  },
  {
    id: 'arm',
    name: 'Station arm',
    kind: 'extrusion',
    dims: { len: 210, s: 20 },
    qty: 1,
    unitEur: 6,
    mount: { frame: 'base', position: [210, 0, CHAIN_Z_MM - 40], rotation: [0, 90, 0] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: 'Sewing-machine arm. The stitch station never orbits the hat.',
    build: (d) => box(d.len, d.s, d.s),
  },
  {
    id: 'carriage',
    name: 'Needle carriage',
    kind: 'printed',
    dims: { x: 54, y: 36, z: 22 },
    qty: 1,
    unitEur: 3,
    mount: { frame: 'H', position: [0, 0, 0] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: 'Rides MGN9. H is the only insertion axis.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'needle',
    name: 'Latch needle',
    kind: 'cots',
    dims: { len: 46, r: 1.1 },
    qty: 6,
    unitEur: 0.8,
    mount: { frame: 'L', position: [-23, 0, 0], rotation: [0, 0, 0] },
    explodeDir: [-1, 0, 0],
    group: 'station',
    note: 'Brother / Passap spare latch needles. Keep five extras.',
    build: (d) => merge([rodX(d.r, d.len, 8, 0), rodX(1.8, 8, 6, -d.len / 2 + 2)]),
  },
  {
    id: 'motor-h',
    name: 'H-axis motor',
    kind: 'motor',
    dims: { s: 42, l: 34 },
    qty: 1,
    unitEur: 14,
    mount: { frame: 'base', position: [248, 0, CHAIN_Z_MM], rotation: [0, 0, 90] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: 'Belt-driven radial slide.',
    build: (d) => stepper(d.s, d.l),
  },
  {
    id: 'motor-l',
    name: 'Latch servo',
    kind: 'motor',
    dims: { s: 20, l: 22 },
    qty: 1,
    unitEur: 8,
    mount: { frame: 'H', position: [12, 16, 18] },
    explodeDir: [0, 1, 0],
    group: 'station',
    note: 'Cam on the latch. Could be a 9g servo.',
    build: (d) => box(d.s, d.s, d.l),
  },
  {
    id: 'injector',
    name: 'Gate magazine',
    kind: 'printed',
    dims: { x: 28, y: 64, z: 22 },
    qty: 1,
    unitEur: 5,
    mount: { frame: 'I', position: [0, 0, 0] },
    explodeDir: [0, 1, 0],
    group: 'station',
    note: 'Holds ~80 spare printed gates. Increase = one push.',
    build: (d) => merge([box(d.x, d.y, d.z), box(d.x - 8, d.y - 8, 4, 14)]),
  },
  {
    id: 'turret',
    name: 'Yarn turret',
    kind: 'printed',
    dims: { r: 28, h: 16 },
    qty: 1,
    unitEur: 4,
    mount: { frame: 'T', position: [0, 0, 0] },
    explodeDir: [0, 0, 1],
    group: 'yarn',
    note: 'Four detents, one colour each. Indexes on the second yarn-over.',
    build: (d) => merge([rodZ(d.r, d.h), rodZ(6, d.h + 10, 12, 8)]),
  },
  {
    id: 'cone',
    name: 'Yarn cone stand',
    kind: 'printed',
    dims: { r: 18, h: 70 },
    qty: 4,
    unitEur: 2,
    mount: { frame: 'base', position: [80, -210, 40] },
    repeats: [
      { position: [30, -230, 40] },
      { position: [-20, -230, 40] },
      { position: [-70, -210, 40] },
    ],
    explodeDir: [0, -1, 0],
    group: 'yarn',
    note: 'DK cotton cones. Dancers sit on the posts above.',
    build: (d) => coneZ(d.r, 6, d.h, 16),
  },
  {
    id: 'dancer',
    name: 'Tension dancer',
    kind: 'cots',
    dims: { r: 8, h: 4 },
    qty: 4,
    unitEur: 3,
    mount: { frame: 'base', position: [80, -168, 118] },
    repeats: [
      { position: [30, -188, 118] },
      { position: [-20, -188, 118] },
      { position: [-70, -168, 118] },
    ],
    explodeDir: [0, 0, 1],
    group: 'yarn',
    note: 'Spring arm + AS5600 encoder. Active tension is what CroMat lacked.',
    build: (d) => rodY(d.r, 18),
  },
  {
    id: 'pi',
    name: 'Raspberry Pi 5',
    kind: 'electronic',
    dims: { x: 88, y: 58, z: 20 },
    qty: 1,
    unitEur: 72,
    mount: { frame: 'base', position: [-160, 140, 22] },
    explodeDir: [-1, 1, 0],
    group: 'control',
    note: 'Plans the job. MCU (Octopus / SKR) steps the motors.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'mcu',
    name: 'Motion MCU',
    kind: 'electronic',
    dims: { x: 110, y: 76, z: 18 },
    qty: 1,
    unitEur: 38,
    mount: { frame: 'base', position: [-160, 60, 20] },
    explodeDir: [-1, 0, 0],
    group: 'control',
    note: 'BTT Octopus or SKR 3, 6× TMC2209 in UART.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'psu',
    name: '24 V PSU',
    kind: 'cots',
    dims: { x: 130, y: 50, z: 32 },
    qty: 1,
    unitEur: 22,
    mount: { frame: 'base', position: [-155, -40, 28] },
    explodeDir: [-1, -1, 0],
    group: 'control',
    note: '350 W Mean Well class. E-stop on the 24 V rail.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'camera',
    name: 'Pi Camera 3',
    kind: 'electronic',
    dims: { x: 24, y: 24, z: 10 },
    qty: 1,
    unitEur: 28,
    mount: { frame: 'base', position: [40, 175, CHAIN_Z_MM + 55] },
    explodeDir: [0, 1, 1],
    group: 'control',
    note: 'Per-round audit, not per-stitch vision. That is the point.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'accent-bar',
    name: 'Station flag',
    kind: 'accent',
    dims: { x: 8, y: 8, z: 48 },
    qty: 1,
    unitEur: 0,
    mount: { frame: 'H', position: [18, -8, 28] },
    explodeDir: [0, 0, 1],
    group: 'station',
    note: 'Painted IKEA yellow so the working point is obvious in photos.',
    build: (d) => box(d.x, d.y, d.z),
  },
];

export const PARTS: readonly PartDef[] = P;
