/**
 * The build, step by step. Bilingual and deliberately terse.
 *
 * Fastener callouts are structured ({sku, qty}) so the harness can sum them
 * across every step and fail if one asks for a screw that never made the
 * shopping list. Every step ends with a `check` — something observable. That is
 * IKEA's real trick, far more than the diagrams: you are never more than one
 * step from knowing you got it wrong.
 */

export type Track = 'station' | 'machine';

export interface GuideStep {
  n: number;
  track: Track;
  title: string;
  titleNo: string;
  body: string;
  bodyNo: string;
  /** Part ids consumed. Drives the 3D highlight and the coverage check. */
  parts: string[];
  uses: { sku: string; qty: number }[];
  check: string;
  checkNo: string;
  minutes: number;
  warn?: string;
  warnNo?: string;
}

export const FASTENERS: Record<string, { label: string; labelNo: string; lenMm: number | null }> = {
  'M3x8-SHCS': { label: 'M3 × 8 cap screw', labelNo: 'M3 × 8 unbrakoskrue', lenMm: 8 },
  'M3x10-SHCS': { label: 'M3 × 10 cap screw', labelNo: 'M3 × 10 unbrakoskrue', lenMm: 10 },
  'M3x16-SHCS': { label: 'M3 × 16 cap screw', labelNo: 'M3 × 16 unbrakoskrue', lenMm: 16 },
  'M3x20-SHCS': { label: 'M3 × 20 cap screw', labelNo: 'M3 × 20 unbrakoskrue', lenMm: 20 },
  'M3-NUT': { label: 'M3 nyloc nut', labelNo: 'M3 låsemutter', lenMm: null },
  'M3-INSERT': { label: 'M3 brass insert', labelNo: 'M3 gjengeinnsats', lenMm: null },
  'M4-INSERT': { label: 'M4 brass insert', labelNo: 'M4 gjengeinnsats', lenMm: null },
  'M4x12-SHCS': { label: 'M4 × 12 cap screw', labelNo: 'M4 × 12 unbrakoskrue', lenMm: 12 },
  'M4-NUT': { label: 'M4 nyloc nut', labelNo: 'M4 låsemutter', lenMm: null },
  'M5x10-BHCS': { label: 'M5 × 10 button screw', labelNo: 'M5 × 10 linseskrue', lenMm: 10 },
  'M5x16-BHCS': { label: 'M5 × 16 button screw', labelNo: 'M5 × 16 linseskrue', lenMm: 16 },
  'M5-TNUT': { label: 'M5 T-nut, 2020', labelNo: 'M5 T-mutter, 2020', lenMm: null },
};

export const STEPS: readonly GuideStep[] = [
  {
    n: 1,
    track: 'station',
    title: 'Print the fit check first',
    titleNo: 'Skriv ut passkontrollen først',
    body: 'Print one gate and one wheel tooth — 20 minutes. Push the gate tongue into the tooth seat. Firm thumb pressure, and it stays put upside down.',
    bodyNo: 'Skriv ut én port og én hjultann — 20 minutter. Trykk tungen inn i tannsetet. Fast tommeltrykk, og den skal sitte når du snur den opp ned.',
    parts: ['gate-8', 'wheel-tooth'],
    uses: [],
    check: 'It seats by thumb and does not fall out inverted. If not, adjust slicer compensation — not the model.',
    checkNo: 'Den sitter med tommelen og faller ikke ut opp ned. Hvis ikke: juster kompensasjon i slicer — ikke modellen.',
    minutes: 30,
  },
  {
    n: 2,
    track: 'station',
    title: 'Print the rest',
    titleNo: 'Skriv ut resten',
    body: '343 g. PETG for anything structural or near a motor, PLA for the camera pod. Print all four gate widths — the bench test picks the winner.',
    bodyNo: '343 g. PETG til alt som bærer eller sitter nær en motor, PLA til kamerahuset. Skriv ut alle fire halsbredder — benketesten avgjør.',
    parts: ['gate-6', 'gate-7', 'gate-7p5', 'gate-8', 'comb-segment', 'needle-collet', 'rail-bracket', 'nema17-mount', 'camera-pod', 'tension-dancer', 'yarn-finger', 'bench-base'],
    uses: [],
    check: 'No layer splits, no lifted corners.',
    checkNo: 'Ingen lagsprekker, ingen løftede hjørner.',
    minutes: 40,
  },
  {
    n: 3,
    track: 'station',
    title: 'Melt in the inserts',
    titleNo: 'Smelt inn innsatsene',
    body: 'Soldering iron at 240 °C. Four M4 in the base, two M3 in the camera pod. Straight down, square to the surface.',
    bodyNo: 'Loddebolt på 240 °C. Fire M4 i bunnplaten, to M3 i kamerahuset. Rett ned, vinkelrett på flaten.',
    parts: ['bench-base', 'camera-pod'],
    uses: [
      { sku: 'M4-INSERT', qty: 4 },
      { sku: 'M3-INSERT', qty: 2 },
    ],
    check: 'Flush or a hair below, and square.',
    checkNo: 'I flukt eller så vidt under, og rett.',
    minutes: 20,
    warn: 'Molten plastic and a 240 °C iron. Ventilate.',
    warnNo: 'Smeltet plast og 240 °C. Luft ut.',
  },
  {
    n: 4,
    track: 'station',
    title: 'Rail and brackets',
    titleNo: 'Skinne og bratter',
    body: 'Cut 200 mm of MGN9, deburr both ends. Brackets to the base, rail to the brackets, finger-tight. Slide the carriage on from one end.',
    bodyNo: 'Kapp 200 mm MGN9, avgrad begge ender. Bratter på bunnplaten, skinne på brattene, fingerstramt. Skyv vognen på fra én ende.',
    parts: ['rail-bracket'],
    uses: [
      { sku: 'M3x10-SHCS', qty: 6 },
      { sku: 'M5x10-BHCS', qty: 4 },
      { sku: 'M5-TNUT', qty: 4 },
    ],
    check: 'The carriage slides the full length with one finger, no tight spot.',
    checkNo: 'Vognen glir hele veien med én finger, uten trange punkter.',
    minutes: 30,
    warn: 'Never run the carriage off the rail end — the balls fall out and it is finished.',
    warnNo: 'Kjør aldri vognen av skinneenden — kulene faller ut og den er ødelagt.',
  },
  {
    n: 5,
    track: 'station',
    title: 'Needle collet',
    titleNo: 'Nålholder',
    body: 'Collet onto the carriage. Ryanål into the bore, latch up and facing the comb. Pinch the clamp slit.',
    bodyNo: 'Holderen på vognen. Ryanål i hullet, klaffen opp og mot kammen. Klem sammen klemsporet.',
    parts: ['needle-collet'],
    uses: [
      { sku: 'M3x10-SHCS', qty: 4 },
      { sku: 'M3x20-SHCS', qty: 1 },
      { sku: 'M3-NUT', qty: 1 },
    ],
    check: 'The needle will not twist by hand, and the latch swings free.',
    checkNo: 'Nålen lar seg ikke vri for hånd, og klaffen svinger fritt.',
    minutes: 20,
    warn: 'Hand tight plus a quarter turn. You are clamping printed plastic.',
    warnNo: 'Fingerstramt pluss en kvart omdreining. Du klemmer på printet plast.',
  },
  {
    n: 6,
    track: 'station',
    title: 'Mount the comb',
    titleNo: 'Monter kammen',
    body: 'Comb to the base, pockets facing the needle. Three gates in — note the stagger: 1 and 3 near row, 2 far row. Leave the ear bolts loose.',
    bodyNo: 'Kammen på bunnplaten, lommene mot nålen. Tre porter i — merk forskyvningen: 1 og 3 i nær rad, 2 i fjern rad. La ørebolt­ene være løse.',
    parts: ['comb-segment', 'gate-8'],
    uses: [
      { sku: 'M3x16-SHCS', qty: 2 },
      { sku: 'M3-NUT', qty: 2 },
    ],
    check: 'Three gates seated, tongues home, none rocking.',
    checkNo: 'Tre porter på plass, tunger i bunn, ingen som vipper.',
    minutes: 20,
  },
  {
    n: 7,
    track: 'station',
    title: 'Motors, wheel, finger',
    titleNo: 'Motorer, hjul, finger',
    body: 'Thermistor into each motor mount pocket before the motor goes on. Shaft through two 608s, tooth on, grub locked. Finger onto the servo horn with 40 mm of filament as the wire tip.',
    bodyNo: 'Termistor i lommen på hvert motorfeste før motoren monteres. Aksel gjennom to 608-lager, tann på, pinneskrue i. Fingeren på servohornet med 40 mm filament som spiss.',
    parts: ['nema17-mount', 'wheel-tooth', 'wheel-shaft', 'yarn-finger'],
    uses: [
      { sku: 'M3x16-SHCS', qty: 8 },
      { sku: 'M5x10-BHCS', qty: 4 },
      { sku: 'M5-TNUT', qty: 4 },
      { sku: 'M3x10-SHCS', qty: 2 },
    ],
    check: 'Both motors spin freely by hand; both thermistors touch motor metal.',
    checkNo: 'Begge motorer går fritt for hånd; begge termistorer ligger mot motormetall.',
    minutes: 45,
    warn: 'Fit the thermistors now. They are the only thing between a stalled motor and a fire.',
    warnNo: 'Monter termistorene nå. De er det eneste mellom en fastkjørt motor og brann.',
  },
  {
    n: 8,
    track: 'station',
    title: 'Wire it — fuse first',
    titleNo: 'Kobling — sikring først',
    body: 'Fuse on the PSU positive, then the E-stop in the same line. Drivers, motors with ferrules, thermistors to analogue in, LED to 12 V constant. Do not power up yet.',
    bodyNo: 'Sikring på pluss fra strømforsyningen, så nødstopp i samme linje. Drivere, motorer med hylser, termistorer til analog inn, LED på konstant 12 V. Ikke slå på ennå.',
    parts: [],
    uses: [],
    check: 'E-stop pressed reads open circuit on the motor supply.',
    checkNo: 'Nødstopp inne gir brutt krets på motorforsyningen.',
    minutes: 45,
    warn: 'The E-stop must break motor POWER, not signal a pin. Software cannot override a broken circuit.',
    warnNo: 'Nødstoppen må bryte STRØMMEN til motorene, ikke gi signal til en pinne. Programvare kan ikke overstyre en brutt krets.',
  },
  {
    n: 9,
    track: 'station',
    title: 'Camera, light, power on',
    titleNo: 'Kamera, lys, oppstart',
    body: 'Aim the pod so the middle gate throat fills a third of the frame. Lock focus manually. LED across the throat, not down it. Power on with a hand on the E-stop and jog each axis 1 mm.',
    bodyNo: 'Rett huset så halsen på midterste port fyller en tredel av bildet. Lås fokus manuelt. LED på tvers av halsen, ikke ned i den. Slå på med hånden på nødstoppen og kjør hver akse 1 mm.',
    parts: ['camera-pod'],
    uses: [
      { sku: 'M3x8-SHCS', qty: 2 },
      { sku: 'M5x10-BHCS', qty: 1 },
      { sku: 'M5-TNUT', qty: 1 },
    ],
    check: 'Both axes jog the right way; both thermistors read room temperature.',
    checkNo: 'Begge akser går riktig vei; begge termistorer viser romtemperatur.',
    minutes: 40,
    warn: 'A sensor reading 0 or absurdly high is disconnected. Fix it before running anything.',
    warnNo: 'En føler som viser 0 eller absurd høyt er frakoblet. Fiks det før du kjører noe.',
  },
  {
    n: 10,
    track: 'station',
    title: 'T0 · T1 — capture and hold',
    titleNo: 'T0 · T1 — fangst og hold',
    body: 'By hand. Hook and release a cotton loop 100 times. Then crochet ten stitches by hand, drop one mouth into a gate, and push the needle through it 50 times.',
    bodyNo: 'For hånd. Fang og slipp en bomullsløkke 100 ganger. Hekle så ti masker for hånd, legg én maskemunn i en port, og før nålen gjennom 50 ganger.',
    parts: [],
    uses: [],
    check: 'T0 100/100 captures. T1 50/50 passes without splitting the yarn.',
    checkNo: 'T0 100/100 fangster. T1 50/50 gjennomføringer uten å splitte garnet.',
    minutes: 60,
  },
  {
    n: 11,
    track: 'station',
    title: 'T2 — the one that matters',
    titleNo: 'T2 — den avgjørende',
    body: 'Tension the swatch so three mouths sit in three gates. Run the tooth through its pickup arc: does it take the loop out of the gate and carry it? Fifty times, logged, camera recording.',
    bodyNo: 'Stram prøvelappen så tre maskemunner ligger i tre porter. Kjør tannen gjennom opptaksbuen: tar den løkken ut av porten og bærer den? Femti ganger, logget, med kamera.',
    parts: [],
    uses: [],
    check: '50/50 pickups. Below 40/50, drop to the next throat width before changing anything else.',
    checkNo: '50/50 opptak. Under 40/50: gå ned én halsbredde før du endrer noe annet.',
    minutes: 120,
    warn: 'If every width fails, the answer is a thinner needle — not a wider throat. There is no room for a wider throat.',
    warnNo: 'Hvis alle bredder feiler er svaret en tynnere nål — ikke en bredere hals. Det er ikke plass til en bredere hals.',
  },
  {
    n: 12,
    track: 'station',
    title: 'T3 — one real stitch',
    titleNo: 'T3 — én ekte maske',
    body: 'Yarn through dancer and eyelet to the finger. Full cycle: pick up, plunge, yarn over, draw through two. Exactly one loop left. Fifty in a row, export the log.',
    bodyNo: 'Garn gjennom strammer og øye til fingeren. Full syklus: ta opp, stikk, legg garn, trekk gjennom to. Nøyaktig én løkke igjen. Femti på rad, eksporter loggen.',
    parts: ['tension-dancer'],
    uses: [
      { sku: 'M3x20-SHCS', qty: 1 },
      { sku: 'M3-NUT', qty: 1 },
    ],
    check: '50 consecutive, one loop each, height spread under 0.6 mm.',
    checkNo: '50 på rad, én løkke hver, høydespredning under 0,6 mm.',
    minutes: 180,
  },
];

export const MACHINE_STEPS: readonly GuideStep[] = [
  {
    n: 13,
    track: 'machine',
    title: 'Cut the deck',
    titleNo: 'Kapp dekket',
    body: 'Four 2020 lengths into a 520 × 420 mm frame, plus two cross members.',
    bodyNo: 'Fire 2020-lengder til en ramme på 520 × 420 mm, pluss to tverrstag.',
    parts: [],
    uses: [
      { sku: 'M5x16-BHCS', qty: 12 },
      { sku: 'M5-TNUT', qty: 12 },
    ],
    check: 'Diagonals match within 1 mm and it does not rock.',
    checkNo: 'Diagonalene er like innen 1 mm og den vipper ikke.',
    minutes: 45,
  },
  {
    n: 14,
    track: 'machine',
    title: 'Seat the turntable bearing',
    titleNo: 'Monter dreielageret',
    body: 'Lazy-susan to the deck centre, hub adapter on top. This bearing is bought, never printed — it is the machine’s concentricity.',
    bodyNo: 'Dreielager i midten av dekket, navadapter oppå. Lageret kjøpes, aldri printes — det er maskinens senterpresisjon.',
    parts: ['hub-adapter'],
    uses: [
      { sku: 'M4x12-SHCS', qty: 4 },
      { sku: 'M5x10-BHCS', qty: 6 },
    ],
    check: 'The hub turns smoothly through a full revolution.',
    checkNo: 'Navet går jevnt en hel omdreining.',
    minutes: 30,
  },
  {
    n: 15,
    track: 'machine',
    title: 'Platter and C belt',
    titleNo: 'Dreieskive og C-rem',
    body: 'Platter onto the hub, GT2 around the rim groove to a 20T pulley. Driving the 240 mm rim gives ~34:1 with no gearbox.',
    bodyNo: 'Skiven på navet, GT2 rundt kantsporet til en 20T remskive. Drift på 240 mm-kanten gir ~34:1 uten girkasse.',
    parts: ['platter'],
    uses: [{ sku: 'M5x10-BHCS', qty: 6 }],
    check: 'Rim runout under 0.3 mm; belt does not slip when you resist by hand.',
    checkNo: 'Kantkast under 0,3 mm; remmen glipper ikke når du holder igjen.',
    minutes: 45,
    warn: 'Every stitch position for 3 694 stitches is measured from this disc. Check runout now.',
    warnNo: 'Hver maskeposisjon i 3 694 masker måles fra denne skiven. Sjekk kastet nå.',
  },
  {
    n: 16,
    track: 'machine',
    title: 'Assemble the mandrel',
    titleNo: 'Sett sammen mandrellen',
    body: 'Three sections, bayonet twist-lock, crown on top. Lathed from the app’s own hat profile, so the former is the shape the pattern makes.',
    bodyNo: 'Tre deler, bajonettlås, kronen øverst. Dreid fra appens egen lueprofil, så formen er den formen oppskriften faktisk lager.',
    parts: ['mandrel-brim', 'mandrel-wall', 'mandrel-crown'],
    uses: [],
    check: 'They twist together without force; under 0.5 mm wobble at the crown.',
    checkNo: 'De vris sammen uten makt; under 0,5 mm kast ved kronen.',
    minutes: 30,
  },
  {
    n: 17,
    track: 'machine',
    title: 'Z column and R carriage',
    titleNo: 'Z-søyle og R-slede',
    body: 'Two brackets to the deck, 2020 column between them, trammed vertical. T8 screw for Z. R rides the rest of the MGN9 metre.',
    bodyNo: 'To bratter på dekket, 2020-søyle mellom dem, rettet loddrett. T8-skrue til Z. R går på resten av MGN9-meteren.',
    parts: ['column-bracket'],
    uses: [
      { sku: 'M5x10-BHCS', qty: 8 },
      { sku: 'M5-TNUT', qty: 8 },
      { sku: 'M4-INSERT', qty: 4 },
    ],
    check: 'Vertical within 0.5 mm over its height, squared off the platter.',
    checkNo: 'Loddrett innen 0,5 mm over høyden, målt mot skiven.',
    minutes: 60,
  },
  {
    n: 18,
    track: 'machine',
    title: 'Move the Station across',
    titleNo: 'Flytt stasjonen over',
    body: 'Unbolt the Station from the bench plate — collet, rail, wheel motor, finger, camera, thermistors, all still bolted together — and bolt it onto the R carriage. Nothing is rebuilt. The bench plate is the only thing left behind.',
    bodyNo: 'Skru stasjonen av benkeplaten — holder, skinne, hjulmotor, finger, kamera, termistorer, alt fortsatt sammenskrudd — og skru den på R-sleden. Ingenting bygges om. Benkeplaten er det eneste som blir igjen.',
    parts: [],
    uses: [
      { sku: 'M5x10-BHCS', qty: 4 },
      { sku: 'M5-TNUT', qty: 4 },
    ],
    check: 'The Station faces the mandrel and P still plunges exactly as on the bench.',
    checkNo: 'Stasjonen peker mot mandrellen og P stikker nøyaktig som på benken.',
    minutes: 45,
  },
  {
    n: 19,
    track: 'machine',
    title: 'Full comb arc',
    titleNo: 'Hele holdekammen',
    body: 'The 10-gate arc replaces the 3-gate segment. Same pitch, same seats, same gates — there are just more of them.',
    bodyNo: 'Buen med 10 porter erstatter segmentet med 3. Samme deling, samme seter, samme porter — bare flere.',
    parts: ['comb-arc'],
    uses: [
      { sku: 'M4x12-SHCS', qty: 2 },
      { sku: 'M4-NUT', qty: 2 },
    ],
    check: 'All ten seat, and the tooth clears every one by the same margin.',
    checkNo: 'Alle ti sitter, og tannen klarerer hver av dem med samme margin.',
    minutes: 30,
  },
  {
    n: 20,
    track: 'machine',
    title: 'Build the eight-tooth wheel',
    titleNo: 'Bygg åttetannshjulet',
    body: 'Eight teeth into the hub, each locked with a grub screw. Belt to the motor at 3:1.',
    bodyNo: 'Åtte tenner i navet, hver låst med pinneskrue. Rem til motoren på 3:1.',
    parts: ['wheel-hub', 'wheel-tooth'],
    uses: [{ sku: 'M3x10-SHCS', qty: 8 }],
    check: 'All eight pass the comb at the same height within 0.2 mm.',
    checkNo: 'Alle åtte passerer kammen i samme høyde innen 0,2 mm.',
    minutes: 40,
  },
  {
    n: 21,
    track: 'machine',
    title: 'Turret and four cones',
    titleNo: 'Karusell og fire koner',
    body: 'Turret onto the T motor, four cone stands behind, one dancer and one ceramic eyelet per colour.',
    bodyNo: 'Karusellen på T-motoren, fire konestativ bak, én strammer og ett keramisk øye per farge.',
    parts: ['turret-drum', 'tension-dancer'],
    uses: [
      { sku: 'M3x10-SHCS', qty: 2 },
      { sku: 'M3x20-SHCS', qty: 4 },
      { sku: 'M3-NUT', qty: 4 },
    ],
    check: 'All four reach the finger; indexing 90° swaps which is presented.',
    checkNo: 'Alle fire når fingeren; 90° indeksering bytter hvilken som presenteres.',
    minutes: 50,
  },
  {
    n: 22,
    track: 'machine',
    title: 'Take-down skirt',
    titleNo: 'Nedtrekkskjørt',
    body: 'The TPU skirt keeps finished fabric off the gates. Without it the hat climbs back into the comb around round 20.',
    bodyNo: 'TPU-skjørtet holder ferdig stoff unna portene. Uten det klatrer lua tilbake i kammen rundt omgang 20.',
    parts: ['takedown-skirt'],
    uses: [{ sku: 'M3x16-SHCS', qty: 3 }],
    check: 'Fingers flex under light pressure and spring back.',
    checkNo: 'Fingrene fjærer under lett trykk og spretter tilbake.',
    minutes: 20,
  },
  {
    n: 23,
    track: 'machine',
    title: 'Remaining axes, then the enclosure',
    titleNo: 'Resten av aksene, så kabinettet',
    body: 'C, Z, R and T. A thermistor on every one. Then the panels and a door interlock in series with the E-stop.',
    bodyNo: 'C, Z, R og T. En termistor på hver. Så panelene og en dørbryter i serie med nødstoppen.',
    parts: [],
    uses: [],
    check: 'Opening the door reads open circuit on the motor supply, same as the E-stop.',
    checkNo: 'Å åpne døren gir brutt krets på motorforsyningen, som nødstoppen.',
    minutes: 120,
    warn: 'Six motors now. Confirm every thermistor reads a plausible room temperature before any long run.',
    warnNo: 'Seks motorer nå. Bekreft at hver termistor viser troverdig romtemperatur før lange kjøringer.',
  },
  {
    n: 24,
    track: 'machine',
    title: 'The first hat',
    titleNo: 'Den første lua',
    body: 'Four colours in palette order. Hand-start the ten-stitch ring on the crown — thirty seconds of several hours. Pick a pattern, press Start, watch the first round with a hand on the E-stop.',
    bodyNo: 'Fire farger i palettrekkefølge. Start ringen på ti masker for hånd på kronen — tretti sekunder av flere timer. Velg en oppskrift, trykk Start, følg første omgang med hånden på nødstoppen.',
    parts: [],
    uses: [],
    check: 'A full round completes with the stitch count the pattern predicted.',
    checkNo: 'En hel omgang fullføres med maskeantallet oppskriften forutsa.',
    minutes: 60,
    warn: 'Do not leave it unattended until you have watched it finish a whole hat awake.',
    warnNo: 'Ikke la den gå uten tilsyn før du har sett den fullføre en hel lue mens du er våken.',
  },
];

export const ALL_STEPS: readonly GuideStep[] = [...STEPS, ...MACHINE_STEPS];

export const TOTAL_MINUTES = STEPS.reduce((s, x) => s + x.minutes, 0);
export const MACHINE_MINUTES = MACHINE_STEPS.reduce((s, x) => s + x.minutes, 0);

export function fastenerDemand(track?: Track): Record<string, number> {
  const out: Record<string, number> = {};
  const src = track ? ALL_STEPS.filter((s) => s.track === track) : ALL_STEPS;
  for (const s of src) for (const u of s.uses) out[u.sku] = (out[u.sku] ?? 0) + u.qty;
  return out;
}
