/**
 * The machine's part library — the single source of truth.
 *
 * `dims` is the ONLY place a number lives. It feeds the twin (build()), the parts table,
 * the BOM, the build manual's step text, the STL export and the drawings. Change a plate
 * thickness here and all six update. That property is the reason this is code and not a
 * CAD file we'd have to retype dimensions out of.
 */

import * as THREE from 'three';
import type { FrameId } from './kinematics.ts';
import { BLOCK_PROFILE } from './units.ts';
import { box, tube, tubeX, cone, lathe, extrusion2020, plate, stepper, merge, place, torusZ } from '../cad/primitives.ts';

export type PartKind = 'printed' | 'cots' | 'extrusion' | 'motor' | 'electronic' | 'yarn' | 'workpiece';
export type Vec3 = [number, number, number];

export interface PartDef {
  id: string;
  name: string;
  nameNo: string;
  kind: PartKind;
  /** Millimetres. The only place dimensions are written down. */
  dims: Record<string, number>;
  material?: string;
  qty: number;
  unitEur?: number;
  /** Frame this part rides on. Motion comes from the frame, never from a baked transform. */
  mount: { frame: FrameId; position: Vec3; rotation?: Vec3 };
  /** Extra copies, offset in the same frame. */
  repeats?: { position: Vec3; rotation?: Vec3 }[];
  explodeDir?: Vec3;
  group: 'frame' | 'former' | 'station' | 'head' | 'yarn' | 'control' | 'sensing' | 'workpiece';
  note: string;
  build: (d: Record<string, number>) => THREE.BufferGeometry;
}

const P: PartDef[] = [
  // ---------------------------------------------------------------- frame
  {
    id: 'base-plate',
    name: 'Base plate',
    nameNo: 'Bunnplate',
    kind: 'printed',
    dims: { x: 460, y: 460, t: 10 },
    material: 'PETG / 12 mm plywood',
    qty: 1,
    unitEur: 22,
    mount: { frame: 'base', position: [0, 0, -18] },
    explodeDir: [0, 0, -1],
    group: 'frame',
    note: 'Everything datums off this. Flatness matters more than strength.',
    build: (d) => plate(d.x, d.y, d.t),
  },
  {
    id: 'column',
    name: '2020 column',
    nameNo: 'Søyle 2020',
    kind: 'extrusion',
    dims: { len: 470, section: 20 },
    material: 'Aluminium 2020',
    qty: 4,
    unitEur: 6,
    mount: { frame: 'base', position: [205, 205, -13] },
    repeats: [
      { position: [-205, 205, -13] },
      { position: [205, -205, -13] },
      { position: [-205, -205, -13] },
    ],
    explodeDir: [0, 0, 1],
    group: 'frame',
    note: 'Commodity extrusion. Four corners, tapped ends, no machining.',
    build: (d) => extrusion2020(d.len),
  },
  {
    id: 'top-rail',
    name: 'Top rail',
    nameNo: 'Toppskinne',
    kind: 'extrusion',
    dims: { len: 430, section: 20 },
    material: 'Aluminium 2020',
    qty: 2,
    unitEur: 6,
    mount: { frame: 'base', position: [205, 0, 462], rotation: [90, 0, 0] },
    repeats: [{ position: [-205, 0, 462], rotation: [90, 0, 0] }],
    explodeDir: [0, 0, 1],
    group: 'frame',
    note: 'Ties the columns together and carries the camera mast.',
    build: (d) => place(extrusion2020(d.len), [0, 0, -d.len / 2]),
  },

  // ---------------------------------------------------------------- former
  {
    id: 'turntable-bearing',
    name: 'Turntable bearing',
    nameNo: 'Dreieskivelager',
    kind: 'cots',
    dims: { od: 190, id: 150, h: 14 },
    material: 'Steel, thin-section slewing ring',
    qty: 1,
    unitEur: 32,
    mount: { frame: 'base', position: [0, 0, 0] },
    explodeDir: [0, 0, -1],
    group: 'former',
    note: 'Sets the whole machine’s concentricity. Buy this, never print it.',
    build: (d) => merge([tube(d.od / 2, d.h, 64, d.h / 2), place(tube(d.id / 2, d.h + 2, 64), [0, 0, d.h / 2])]),
  },
  {
    id: 'block-hub',
    name: 'Former hub',
    nameNo: 'Blokknav',
    kind: 'printed',
    dims: { r: 92, h: 16, boreR: 8 },
    material: 'PETG, 40% infill',
    qty: 1,
    unitEur: 4,
    mount: { frame: 'C', position: [0, 0, 14] },
    explodeDir: [0, 0, 1],
    group: 'former',
    note: 'Bolts the former to the bearing inner race. Belt groove on the rim.',
    build: (d) => merge([tube(d.r, d.h, 64, d.h / 2), place(torusZ(d.r - 2, 3), [0, 0, d.h / 2])]),
  },
  {
    id: 'hat-block',
    name: 'Hat-block former',
    nameNo: 'Hatteblokk',
    kind: 'printed',
    dims: { height: 158, maxR: 144, segments: 5 },
    material: 'PETG, 20% gyroid, silicone-sleeved',
    qty: 1,
    unitEur: 18,
    mount: { frame: 'C', position: [0, 0, 30] },
    explodeDir: [0, 0, 1],
    group: 'former',
    note: 'THE central idea. A compliant fabric has no datum, so the machine supplies one. Profile is generated from the same buildProfile() maths the StrikkeApp 3D model uses.',
    build: () => lathe(BLOCK_PROFILE, 96),
  },
  {
    id: 'takedown-skirt',
    name: 'Take-down skirt',
    nameNo: 'Nedtrekksring',
    kind: 'printed',
    dims: { r: 150, h: 8 },
    material: 'TPU 95A',
    qty: 1,
    unitEur: 3,
    mount: { frame: 'C', position: [0, 0, 22] },
    explodeDir: [0, 0, -1],
    group: 'former',
    note: 'Sprung ring that keeps the finished fabric pulled down onto the former. Replaces the hanging weight a knitting machine would use.',
    build: (d) => torusZ(d.r, d.h / 2, 64),
  },
  {
    id: 'motor-c',
    name: 'C motor (block rotation)',
    nameNo: 'C-motor',
    kind: 'motor',
    dims: { len: 40, shaft: 22 },
    material: 'NEMA17, 5:1 belt reduction',
    qty: 1,
    unitEur: 14,
    mount: { frame: 'base', position: [140, 0, -14], rotation: [180, 0, 0] },
    explodeDir: [0, 0, -1],
    group: 'former',
    note: '5:1 gives 0.0225° per microstep = 0.057 mm at the rim — 8× tighter than the 0.5 mm localisation budget.',
    build: (d) => stepper(d.len, d.shaft),
  },

  // ---------------------------------------------------------------- station
  {
    id: 'z-rail',
    name: 'Z linear rail',
    nameNo: 'Z-skinne',
    kind: 'cots',
    dims: { len: 300, w: 12 },
    material: 'MGN12 + carriage',
    qty: 1,
    unitEur: 26,
    mount: { frame: 'base', position: [232, 0, 150] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: 'Precision comes from steel, not from print settings.',
    build: (d) => box(d.w, 24, d.len),
  },
  {
    id: 'z-screw',
    name: 'Z leadscrew',
    nameNo: 'Z-skrue',
    kind: 'cots',
    dims: { len: 300, r: 4, lead: 8 },
    material: 'T8, 8 mm lead',
    qty: 1,
    unitEur: 11,
    mount: { frame: 'base', position: [258, 0, 150] },
    explodeDir: [1, 0, 0],
    group: 'station',
    build: (d) => tube(d.r, d.len, 16),
    note: '8 mm lead: 400 steps/mm at 1/16 microstepping.',
  },
  {
    id: 'motor-z',
    name: 'Z motor',
    nameNo: 'Z-motor',
    kind: 'motor',
    dims: { len: 40, shaft: 20 },
    qty: 1,
    unitEur: 14,
    mount: { frame: 'base', position: [258, 0, 310] },
    explodeDir: [0, 0, 1],
    group: 'station',
    note: 'Direct-drive on the leadscrew.',
    build: (d) => stepper(d.len, d.shaft),
  },
  {
    id: 'z-carriage',
    name: 'Z carriage',
    nameNo: 'Z-vogn',
    kind: 'printed',
    dims: { x: 70, y: 90, t: 10 },
    material: 'PETG, 60% infill',
    qty: 1,
    unitEur: 3,
    mount: { frame: 'Z', position: [238, 0, 0], rotation: [0, 90, 0] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: 'Carries the R axis. Print on edge so layer lines run along the load.',
    build: (d) => plate(d.x, d.y, d.t),
  },
  {
    id: 'r-rail',
    name: 'R linear rail',
    nameNo: 'R-skinne',
    kind: 'cots',
    dims: { len: 210, w: 9 },
    material: 'MGN9 + carriage',
    qty: 1,
    unitEur: 20,
    mount: { frame: 'Z', position: [130, 0, 22], rotation: [0, 0, 0] },
    explodeDir: [0, 0, 1],
    group: 'station',
    note: 'Radial feed. Runs from r=210 (parked, clear of the rim) to r=20 (crown close-out).',
    build: (d) => place(box(d.len, 22, d.w), [0, 0, 0]),
  },
  {
    id: 'motor-r',
    name: 'R motor',
    nameNo: 'R-motor',
    kind: 'motor',
    dims: { len: 34, shaft: 18 },
    qty: 1,
    unitEur: 13,
    mount: { frame: 'Z', position: [244, 0, 22], rotation: [0, -90, 0] },
    explodeDir: [1, 0, 0],
    group: 'station',
    note: '',
    build: (d) => stepper(d.len, d.shaft),
  },
  {
    id: 'r-carriage',
    name: 'R carriage / tilt yoke',
    nameNo: 'R-vogn',
    kind: 'printed',
    dims: { x: 56, y: 62, t: 9 },
    material: 'PETG',
    qty: 1,
    unitEur: 3,
    mount: { frame: 'R', position: [0, 0, 16], rotation: [90, 0, 0] },
    explodeDir: [0, 0, 1],
    group: 'station',
    note: 'Holds the B worm sector. The tilt bearing here is the one printed joint that carries real load.',
    build: (d) => plate(d.x, d.y, d.t),
  },
  {
    id: 'motor-b',
    name: 'B motor (tilt)',
    nameNo: 'B-motor',
    kind: 'motor',
    dims: { len: 30, shaft: 14 },
    qty: 1,
    unitEur: 12,
    mount: { frame: 'R', position: [26, -30, 16], rotation: [90, 0, 0] },
    explodeDir: [0, 1, 0],
    group: 'station',
    note: '40:1 worm. Self-locking, so the tilt holds with the motor unpowered.',
    build: (d) => stepper(d.len, d.shaft),
  },

  // ---------------------------------------------------------------- head
  {
    id: 'head-body',
    name: 'Stitch head body',
    nameNo: 'Maskehode',
    kind: 'printed',
    dims: { x: 74, y: 40, z: 34 },
    material: 'PETG, 50% infill',
    qty: 1,
    unitEur: 5,
    mount: { frame: 'B', position: [22, 0, 0] },
    explodeDir: [1, 0, 0],
    group: 'head',
    note: 'Carries P, G and S. The whole assembly swaps out as one module, so a new head design does not mean a new machine.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'motor-p',
    name: 'P motor (plunge)',
    nameNo: 'P-motor',
    kind: 'motor',
    dims: { len: 34, shaft: 14 },
    qty: 1,
    unitEur: 13,
    mount: { frame: 'B', position: [62, 0, 0], rotation: [0, 90, 0] },
    explodeDir: [1, 0, 0],
    group: 'head',
    note: 'Fast, short-stroke. Its retract depth is the loop height, so gauge is a software value.',
    build: (d) => stepper(d.len, d.shaft),
  },
  {
    id: 'needle-carrier',
    name: 'Needle carrier',
    nameNo: 'Nåleholder',
    kind: 'printed',
    dims: { x: 30, y: 14, z: 12 },
    material: 'PETG with PTFE-lined throat',
    qty: 1,
    unitEur: 2,
    mount: { frame: 'P', position: [8, 0, 0] },
    explodeDir: [1, 0, 0],
    group: 'head',
    note: 'The yarn-contact throat is PTFE tube, never printed plastic — printed layer lines shred yarn.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'latch-needle',
    name: 'Latch needle',
    nameNo: 'Tungenål',
    kind: 'cots',
    dims: { len: 46, r: 0.85 },
    material: 'Steel, 4.5 mm-gauge knitting machine needle',
    qty: 6,
    unitEur: 0.8,
    mount: { frame: 'P', position: [0, 0, 0] },
    explodeDir: [-1, 0, 0],
    group: 'head',
    note: 'Off-the-shelf, ~€0.80 each. Its latch is closed by the loop itself, which removes the hook-rotation degree of freedom entirely.',
    build: (d) =>
      merge([
        tubeX(d.r, d.len, 12, -d.len / 2),
        place(cone(d.r, 0.15, 4, 12), [-d.len + 2, 0, 0], [0, 90, 0]),
        place(tube(0.35, 5, 8), [-d.len + 6, 0, 1.2], [90, 0, 0]),
      ]),
  },
  {
    id: 'presenter-finger',
    name: 'Presenter finger',
    nameNo: 'Presenterfinger',
    kind: 'printed',
    dims: { len: 26, r: 0.4, flexure: 14 },
    material: 'Spring steel 0.8 mm on a TPU flexure',
    qty: 1,
    unitEur: 2,
    mount: { frame: 'G', position: [0, 0, 0] },
    explodeDir: [0, 1, 0],
    group: 'head',
    note: 'Compliance is the point: the taper self-centres into the V and absorbs ±0.4 mm of fabric error mechanically, instead of demanding it of the servos.',
    build: (d) =>
      merge([tubeX(d.r, d.len, 8, -d.len / 2), place(cone(d.r, 0.1, 5, 8), [-d.len + 2, 0, 0], [0, 90, 0])]),
  },
  {
    id: 'selector-carousel',
    name: 'Yarn selector carousel',
    nameNo: 'Garnvelger',
    kind: 'printed',
    dims: { r: 16, h: 12, ports: 4 },
    material: 'PLA body, ceramic eyelets',
    qty: 1,
    unitEur: 6,
    mount: { frame: 'S', position: [0, 0, 0] },
    explodeDir: [0, -1, 0],
    group: 'head',
    note: 'Four detents. Must move BETWEEN the two draw-throughs of one stitch — that mid-stitch window is the strongest novelty claim in the disclosure.',
    build: (d) => {
      const gs = [tube(d.r, d.h, 24, 0)];
      for (let i = 0; i < d.ports; i++) {
        const a = (i / d.ports) * Math.PI * 2;
        gs.push(place(tube(2.2, 6, 12), [Math.cos(a) * (d.r - 3), Math.sin(a) * (d.r - 3), 0]));
      }
      return merge(gs);
    },
  },
  {
    id: 'motor-s',
    name: 'S motor (selector)',
    nameNo: 'S-motor',
    kind: 'motor',
    dims: { len: 26, shaft: 12 },
    qty: 1,
    unitEur: 11,
    mount: { frame: 'B', position: [14, -10, -22] },
    explodeDir: [0, 0, -1],
    group: 'head',
    note: '',
    build: (d) => stepper(d.len, d.shaft),
  },

  // ---------------------------------------------------------------- yarn
  {
    id: 'yarn-cone',
    name: 'Yarn cone',
    nameNo: 'Garnkone',
    kind: 'yarn',
    dims: { r0: 34, r1: 20, h: 110 },
    material: 'DK cotton',
    qty: 4,
    unitEur: 10,
    mount: { frame: 'base', position: [-150, -318, 6] },
    repeats: [
      { position: [-50, -318, 6] },
      { position: [50, -318, 6] },
      { position: [150, -318, 6] },
    ],
    explodeDir: [0, -1, 0],
    group: 'yarn',
    note: 'Four colours — the NORGE Home hat needs red, blue, light blue and white.',
    build: (d) => cone(d.r0, d.r1, d.h, 24, d.h / 2),
  },
  {
    id: 'creel-plate',
    name: 'Creel base',
    nameNo: 'Garnstativ',
    kind: 'printed',
    dims: { x: 400, y: 120, t: 10 },
    material: 'PETG / plywood',
    qty: 1,
    unitEur: 8,
    mount: { frame: 'base', position: [0, -318, 0] },
    explodeDir: [0, -1, 0],
    group: 'yarn',
    note: 'The creel stands outside the frame so a colour can be changed without reaching past the needle.',
    build: (d) => plate(d.x, d.y, d.t),
  },
  {
    id: 'creel-mast',
    name: 'Creel mast',
    nameNo: 'Garnmast',
    kind: 'extrusion',
    dims: { len: 300, section: 20 },
    material: 'Aluminium 2020',
    qty: 2,
    unitEur: 5,
    mount: { frame: 'base', position: [-195, -318, 4] },
    repeats: [{ position: [195, -318, 4] }],
    explodeDir: [0, 0, 1],
    group: 'yarn',
    note: '',
    build: (d) => extrusion2020(d.len),
  },
  {
    id: 'creel-beam',
    name: 'Creel cross beam',
    nameNo: 'Tverrbjelke',
    kind: 'extrusion',
    dims: { len: 400, section: 20 },
    material: 'Aluminium 2020',
    qty: 1,
    unitEur: 5,
    mount: { frame: 'base', position: [0, -318, 292], rotation: [0, 90, 0] },
    explodeDir: [0, 0, 1],
    group: 'yarn',
    note: 'Carries the four dancers and the driven feed rollers.',
    build: (d) => place(extrusion2020(d.len), [0, 0, -d.len / 2]),
  },
  {
    id: 'dancer-arm',
    name: 'Tension dancer',
    nameNo: 'Danserarm',
    kind: 'printed',
    dims: { len: 62, r: 3 },
    material: 'PLA + music-wire spring + AS5600 encoder',
    qty: 4,
    unitEur: 5,
    mount: { frame: 'base', position: [-150, -300, 268], rotation: [0, 40, 0] },
    repeats: [
      { position: [-50, -300, 268], rotation: [0, 40, 0] },
      { position: [50, -300, 268], rotation: [0, 40, 0] },
      { position: [150, -300, 268], rotation: [0, 40, 0] },
    ],
    explodeDir: [0, 0, 1],
    group: 'yarn',
    note: 'Spring arm + magnetic encoder = analogue tension measurement for €3. CroMat explicitly could not run high-friction yarn without this.',
    build: (d) => merge([tubeX(d.r, d.len, 10, d.len / 2), place(tube(6, 4, 16), [d.len, 0, 0])]),
  },
  {
    id: 'feed-roller',
    name: 'Driven feed roller',
    nameNo: 'Matevalse',
    kind: 'printed',
    dims: { r: 12, w: 10 },
    material: 'TPU-tyred PLA hub',
    qty: 4,
    unitEur: 4,
    mount: { frame: 'F1', position: [0, 0, 0], rotation: [90, 0, 0] },
    repeats: [
      { position: [100, 0, 0], rotation: [90, 0, 0] },
      { position: [200, 0, 0], rotation: [90, 0, 0] },
      { position: [300, 0, 0], rotation: [90, 0, 0] },
    ],
    explodeDir: [0, -1, 0],
    group: 'yarn',
    note: 'Also the odometer: the encoder on this roller measures yarn consumed per stitch, which is the machine’s primary pass/fail signal.',
    build: (d) => tube(d.r, d.w, 24),
  },

  // ---------------------------------------------------------------- control + sensing
  {
    id: 'controller-box',
    name: 'Controller enclosure',
    nameNo: 'Styringsboks',
    kind: 'electronic',
    dims: { x: 150, y: 110, z: 55 },
    material: 'Pi 5 + Octopus board + 8× TMC2209',
    qty: 1,
    unitEur: 155,
    mount: { frame: 'base', position: [-110, 292, 30], rotation: [0, 0, 0] },
    explodeDir: [0, 1, 0],
    group: 'control',
    note: 'Klipper: the Pi plans, the MCU steps. We do not write a motion planner.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'psu',
    name: '24 V PSU',
    nameNo: 'Strømforsyning',
    kind: 'electronic',
    dims: { x: 130, y: 60, z: 40 },
    qty: 1,
    unitEur: 30,
    mount: { frame: 'base', position: [110, 292, 22] },
    explodeDir: [0, 1, 0],
    group: 'control',
    note: '350 W. Peak draw ~6 A with all eight steppers energised.',
    build: (d) => box(d.x, d.y, d.z),
  },
  {
    id: 'estop',
    name: 'E-stop',
    nameNo: 'Nødstopp',
    kind: 'electronic',
    dims: { r: 22, h: 20 },
    qty: 1,
    unitEur: 12,
    mount: { frame: 'base', position: [196, 250, 6] },
    explodeDir: [0, 1, 0],
    group: 'control',
    note: 'Latching, wired into the 24 V motor rail — not a software stop. Logic stays alive so the machine can report where it died.',
    build: (d) => merge([tube(d.r, d.h, 24, d.h / 2), place(tube(d.r - 6, 8, 24), [0, 0, d.h])]),
  },
  {
    id: 'camera',
    name: 'Audit camera',
    nameNo: 'Kontrollkamera',
    kind: 'electronic',
    dims: { x: 26, y: 26, z: 14 },
    qty: 1,
    unitEur: 30,
    mount: { frame: 'base', position: [120, 0, 430], rotation: [0, 40, 0] },
    explodeDir: [0, 0, 1],
    group: 'sensing',
    note: 'Fires ONCE PER ROUND, not per stitch: count the round, verify the colour sequence, re-register the seam. Per-stitch verification is done by measuring yarn, which is cheaper and explainable.',
    build: (d) => merge([box(d.x, d.y, d.z), place(tube(7, 10, 20), [0, 0, -8])]),
  },
  {
    id: 'ring-light',
    name: 'LED ring light',
    nameNo: 'Ringlys',
    kind: 'electronic',
    dims: { r: 34, h: 6 },
    qty: 1,
    unitEur: 12,
    mount: { frame: 'base', position: [120, 0, 415], rotation: [0, 40, 0] },
    explodeDir: [0, 0, 1],
    group: 'sensing',
    note: 'Constant illumination so the audit is not fighting room light.',
    build: (d) => torusZ(d.r, d.h / 2, 40),
  },
];

export const PARTS: readonly PartDef[] = P;
export const PART_BY_ID = new Map(P.map((p) => [p.id, p]));

export const GROUP_LABEL: Record<PartDef['group'], string> = {
  frame: 'Ramme',
  former: 'Hatteblokk',
  station: 'Stasjon',
  head: 'Maskehode',
  yarn: 'Garnvei',
  control: 'Styring',
  sensing: 'Sensorer',
  workpiece: 'Arbeidsstykke',
};

export const KIND_COLOR: Record<PartKind, string> = {
  printed: '#E8DFC9',
  cots: '#8D939B',
  extrusion: '#B9BDC2',
  motor: '#2E2C29',
  electronic: '#2F6B4F',
  yarn: '#BA0C2F',
  workpiece: '#BA0C2F',
};

export function totalPartsCost(): number {
  return PARTS.reduce((s, p) => s + (p.unitEur ?? 0) * p.qty, 0);
}
